-- 고객(Client) 테이블 생성
CREATE TABLE TBL_CLIENT (
    CLIENT_NO NUMBER PRIMARY KEY,
    CLIENT_ID VARCHAR2(100),
    CLIENT_PASSWORD VARCHAR2(100),
    CLIENT_NAME VARCHAR2(40),
    CLIENT_STATUS VARCHAR2(10),
    CLIENT_EMAIL VARCHAR2(100),
    CLIENT_PHONE_NUMBER VARCHAR2(20),
    CLIENT_ADDR VARCHAR2(200),
    JOIN_DATE DATE
);

-- 계좌(Account) 테이블 생성
CREATE TABLE TBL_ACCOUNT (
    ACCOUNT_NO VARCHAR2(40) PRIMARY KEY,
    CLIENT_NO NUMBER,
    ACCOUNT_NAME VARCHAR2(100),
    WEALTH NUMBER,
    ACCOUNT_STATUS VARCHAR2(10),
    ACCOUNT_KIND VARCHAR2(40),
    LAST_TRANSACTION_DATE DATE,
    CREATE_DATE DATE
);

-- PK 제약 조건만 있는 새로운 TBL_TRANSACTION 테이블 생성
CREATE TABLE TBL_TRANSACTION (
    TRANSACTION_NO      VARCHAR2(100)       PRIMARY KEY,
    FROM_ACCOUNT        VARCHAR2(40),
    TO_ACCOUNT          VARCHAR2(40),
    TRANSACTION_KIND    VARCHAR2(60),
    AMOUNT              NUMBER,
    TRANSACTION_DATE    DATE,
    MEMO                VARCHAR2(4000)
);

-- TBL_TRANSACTION에 대한 주석 추가 (이전과 동일)
COMMENT ON COLUMN TBL_TRANSACTION.TRANSACTION_NO IS '거래 번호';
COMMENT ON COLUMN TBL_TRANSACTION.FROM_ACCOUNT IS '보낸이 계좌 번호';
COMMENT ON COLUMN TBL_TRANSACTION.TO_ACCOUNT IS '받는이 계좌 번호';
COMMENT ON COLUMN TBL_TRANSACTION.TRANSACTION_KIND IS '거래 종류';
COMMENT ON COLUMN TBL_TRANSACTION.AMOUNT IS '거래량';
COMMENT ON COLUMN TBL_TRANSACTION.TRANSACTION_DATE IS '거래 날짜';
COMMENT ON COLUMN TBL_TRANSACTION.MEMO IS '메모';

-- 시퀀스 생성
-- TBL_CLIENT의 CLIENT_NO 자동 생성을 위한 시퀀스입니다.
CREATE SEQUENCE TBL_CLIENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMIT;
