-- 고객(Client) 테이블 생성
CREATE TABLE TBL_CLIENT (
    CLIENT_NO NUMBER PRIMARY KEY,
    CLIENT_ID VARCHAR2(100),
    CLIENT_PASSWORD VARCHAR2(100),
    CLIENT_NAME VARCHAR2(40),
    CLIENT_STATUS VARCHAR2(10),
    CLIENT_EMAIL VARCHAR2(100),
    CLIENT_PHONE_NUMBER VARCHAR2(20),
    CLIENT_ADDR VARCHAR2(200),
    JOIN_DATE DATE
);

-- 계좌(Account) 테이블 생성
CREATE TABLE TBL_ACCOUNT (
    ACCOUNT_NO VARCHAR2(40) PRIMARY KEY,
    CLIENT_NO NUMBER,
    ACCOUNT_NAME VARCHAR2(100),
    WEALTH NUMBER,
    ACCOUNT_STATUS VARCHAR2(10),
    ACCOUNT_KIND VARCHAR2(40),
    LAST_TRANSACTION_DATE DATE,
    CREATE_DATE DATE
);

-- 거래(Transaction) 테이블 생성
CREATE TABLE TBL_TRANSACTION (
    TRANSACTION_ID VARCHAR2(50) PRIMARY KEY,
    CLIENT_NO_SENDER NUMBER,
    ACCOUNT_NO_SENDER VARCHAR2(40),
    CLIENT_NO_RECEIVER NUMBER,
    ACCOUNT_NO_RECEIVER VARCHAR2(40),
    AMOUNT NUMBER,
    TRANSACTION_DATE DATE
);

-- 시퀀스 생성
-- TBL_CLIENT의 CLIENT_NO 자동 생성을 위한 시퀀스입니다.
CREATE SEQUENCE TBL_CLIENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
